#ifndef GUARD_CONSTANTS_ADOPTION_TIERS_H
#define GUARD_CONSTANTS_ADOPTION_TIERS_H

enum AdoptionTier {
    ADOPTION_TIER_BASIC,
    ADOPTION_TIER_MEDIUM,
    ADOPTION_TIER_TOP,
    ADOPTION_TIER_SUPREME,
    ADOPTION_TIER_LEGENDARY,
    ADOPTION_TIER_SEVII,
    ADOPTION_TIER_COUNT,
};

#endif // GUARD_CONSTANTS_ADOPTION_TIERS_H
