# 1 "data/maps/DiglettGrotto/scripts.pory"

# 2 "data/maps/DiglettGrotto/scripts.pory"
DiglettGrotto_MapScripts::
# 3 "data/maps/DiglettGrotto/scripts.pory"
	.byte 0
# 4 "data/maps/DiglettGrotto/scripts.pory"

# 5 "data/maps/DiglettGrotto/scripts.pory"
DiglettGrotto_EventScript_Man1::
# 6 "data/maps/DiglettGrotto/scripts.pory"
	msgbox DiglettGrotto_Text_Loss, MSGBOX_NPC
# 7 "data/maps/DiglettGrotto/scripts.pory"
	end
# 8 "data/maps/DiglettGrotto/scripts.pory"
	
# 9 "data/maps/DiglettGrotto/scripts.pory"
DiglettGrotto_Text_Loss:
# 10 "data/maps/DiglettGrotto/scripts.pory"
	.string "I come here when I'm at\n"
# 11 "data/maps/DiglettGrotto/scripts.pory"
	.string "a loss for words...$"
